### PR TITLE
Added dictionary attack

### PR DESCRIPTION
**Pull request by dhondta**
This adds a `-w`/`--wordlist` option to perform a dictionary attack on the master password.

### CODE REVIEW

**Comment by unode** [comment]
@dhondta as stated in the README, firefox_decrypt is not a password cracking tool and does not aim to be one.

Thank you for the time you've put into the pull request but I'll have to decline.

I'm sorry.

**Comment by dhondta** [comment]
@unode OK, I expected this answer and I understand. Do you agree if I publish my variant of your tool as a Gist, of course pointing to your excellent work ?

**Comment by unode** [comment]
The code is GPL so you are free to do so. I'm also fine with that too.
The only thing I'd ask is to make it clear this is an added feature and not something officially supported.

**Comment by dhondta** [comment]
@unode Yes, indeed, but that's more a matter of courtesy. OK for the mention, I'll do it. Thank you.

**Comment by unode** [comment]
@dhondta Much appreciated :) and happy to see this little tool used by a security expert ;)

**Pull request closed without merging**
