### PR TITLE
Single minimal profile support

### PR DESCRIPTION
**Pull request by criztovyl**
Adds --single/-s to specify a folder that contains at least a keyX.db, certX.db and logins.json.

I use this for having my Firefox passwords with me on my Ubuntu Touch.

### CODE REVIEW

**Comment by Unode** [comment]
Hi Christoph,

I'm not entirely ok with this change. This argument introduces an entirely separate route to indicate a profile path. I find it makes invoking confusing. Example:

    % firefox_decrypt.py -s here/single_profile /path/to/profiles

I see what you are trying to achieve but this also means a user would need to know the internals of the Mozilla profile and which files to pick. So it would be an advanced usage option.

On the other hand, the overhead of keeping a `profiles.ini` file on your Ubuntu Touch and store the mentioned files on a subfolder should be minimal. You don't actually need all of the profile folder as you pointed out.

I also considered changing the code such that `profile_path` could either be the folder containing `profile.ini` or the actual profile. In the end I decided this would make the approach less generic as I would need to update the code anytime profile name changes were introduced.

--------

In the meantime I've added an option to automatically load the profile if only a single profile exists. This should behave the same as your patch as long as `profiles.ini` is in place. Meaning:

    % firefox_decrypt.py /path/to/profiles

where /path/to/profiles contains

    /path/to/profiles
    ├── mine
    │   ├── certX.db
    │   ├── keyX.db
    │   ├── logins.json
    │   └── ...
    └── profiles.ini

and

    % cat /path/to/profiles/profiles.ini
    [Profile0]
    Path=mine

Feel free to reopen if you think there's a better way.

**Comment by criztovyl** [comment]
Hey,
thanks for your response :)

I agree with you in general but do not understand what you mean by "profile name changes".

Wouldn't it be generic to check the presence of the `profiles.ini` to decide whether to load a single profile?

**Comment by Unode** [comment]
As you pointed out, the number next to keyX.db and certX.db has changed in the past. This is what I meant by "profile name changes". I never bothered to check how frequently though. I see now it didn't change as frequently as I thought. cert7.db is quite old.

The storage backend was also `sqlite` in the past and is currently `json` for newer versions of firefox. This I had to implement since I needed to get the hashed passwords.

To minimize tracking effort on my part I decided not to rely on the existence of the files and simply let libnss handle it. The errors produced by libnss when files are missing are also not always clear. Given all this I decided to simplify the usage and not detail which files are necessary for password decryption. Using the `profiles.ini` file ensures this to a large degree as most users will be using their entire firefox/thunderbird profiles folder.

I hope that clarifies the motivation behind this decision.

Cheers,
R

**Comment by criztovyl** [comment]
Sure.
So if we drop the "minimal" everything would be okay?

**Comment by criztovyl** [comment]
https://github.com/criztovyl/firefox_decrypt/commit/e95250991e6b5e53e383fb7aeb11645315a5771e

**Comment by Unode** [comment]
Implemented on 0.4.2

**Comment by criztovyl** [comment]
Cool.
Thanks for your effords :)

**Pull request closed without merging**
