### PR TITLE
Non-interactive mode

### PR DESCRIPTION
**Pull request by criztovyl**

### CODE REVIEW

**Comment by Unode** [comment]
@criztovyl I'm mostly ok with it but I'd like to see some tests for this functionality 

On minor points:
* The `ljst` variable is a bit strange. If you can rename that to `display`, `show` or `list_profiles` I'd prefer.
* There's also `textIOWrapper` which I don't see the need for. It looks over engineered.
* Line [589](https://github.com/Unode/firefox_decrypt/pull/6/files#diff-1414aa7f803aa0fc1f720d9ebf9dbb86R589) , no need for `str()` there. Use a literal `'1'`.

**Comment by criztovyl** [comment]
Will fix 1 & 3.
I use the `textIOWrapper` to print the profile list from `-l/--list` to stdout. (information belong there, not to stderr ^^)

**Comment by Unode** [comment]
Looks good. I had missed the `--list` to `sys.stdout`.
And about the tests, would you mind including some?

**Comment by criztovyl** [comment]
Would really like to add some tests. I already looked into the directory, but I don't understand what happens ^^
Could you point me somewhere?

**Comment by Unode** [comment]
The tests are a little bit odd indeed. There isn't so much documentation.
Basically each set of tests is one file with the ".t" extension. Then for each file, there's the `bash_tap_fd.sh` that is sourced and does all the magic.
Each line is then executed and if the final command exits with a non-zero the test is considered a failure.
The use of "diff | grep" is a way to check if the expected output is present or not. Since `grep` exits with non-zero when there's no match, that causes tests to fail.

The other syntax `<()` is [bash process substitution](http://www.tldp.org/LDP/abs/html/process-sub.html).

**Comment by Unode** [comment]
Thanks @criztovyl awesome work.

**Comment by criztovyl** [comment]
Thank you.

**Pull request merged**
