### PR TITLE
Updated firefox_decrypt.py error message

### PR DESCRIPTION
**Pull request by go9girl**
adds hint to fix Profile location not found error

### CODE REVIEW

**Comment by unode** [comment]
Hi @go9girl, I appreciate the contribution but this is already covered [in the documentation](https://github.com/unode/firefox_decrypt?tab=readme-ov-file#advanced-usage) as well as `--help`.

If you think documentation is insufficient, I'm happy to include improvements there.

**Comment by go9girl** [comment]
The documentation is sufficient to fix the issue but i fell it would safe everyone encountering the issue a few minutes of their time

**Comment by unode** [comment]
I'm reluctant to add the extra message to the error because the error can be shown for other reasons where the extra message would be confusing. Consider:

```
% ./firefox_decrypt.py /path/not/found
2024-03-18 11:17:57,806 - WARNING - profile.ini not found in /path/not/found
2024-03-18 11:17:57,806 - WARNING - Continuing and assuming '/path/not/found' is a profile location
2024-03-18 11:17:57,807 - ERROR - Profile location '/path/not/found' is not a directory

% ./firefox_decrypt.py /dev/null
2024-03-18 11:18:17,019 - WARNING - profile.ini not found in /dev/null
2024-03-18 11:18:17,019 - WARNING - Continuing and assuming '/dev/null' is a profile location
2024-03-18 11:18:17,019 - ERROR - Profile location '/dev/null' is not a directory

% ./firefox_decrypt.py /dev/
2024-03-18 11:18:21,720 - WARNING - profile.ini not found in /dev/
2024-03-18 11:18:21,720 - WARNING - Continuing and assuming '/dev/' is a profile location
2024-03-18 11:18:21,724 - ERROR - Couldn't initialize NSS, maybe '/dev/' is not a valid profile?
```

**Comment by unode** [comment]
Hi @go9girl

I have [credited you for your contribution](https://github.com/unode/firefox_decrypt/commit/2a163faf6c22f62eb0b061fa3c0b317ae2e4a343) but following the explanation above I'm rejecting this change.

Thank you for the time you took and the suggestion.

**Pull request closed without merging**
